[Feat] 개발 서버 배포 자동화 (CD)
ecolink-JOIN/JOIN-BE pull request #4
Opened 2024-07-23 09:48 UTC by uuujini

## 📌 관련 이슈
- #1 

## ✨ PR 내용
- 개발 서버 배포 자동화를 위한 GHA 스크립트 추가

## 📚 레퍼런스 혹은 궁금한 사항들

## 📸 스크린샷(선택)

2024-07-23 12:49 UTC, wnsvy607 requested changes

2024-07-23 12:49 UTC, wnsvy607 commented on .github/workflows/deploy-dev.yml
> +        run: docker run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=map2zero mysql:8.0.31
이 부분에서 기본 생성되는 데이터베이스 이름이 
`map2zero` 인데
application.yml 파일에 설정된 `local_db`로 바꾸는게 좋을 것 같아요!

2024-07-23 12:49 UTC, wnsvy607 commented on .github/workflows/test-action.yml
> +        run: docker run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=map2zero mysql:8.0.31
여기도!

2024-07-23 12:49 UTC, wnsvy607 commented on src/main/resources/application.yml
> +        dialect: org.hibernate.dialect.MySQL8Dialect
이 부분은 어떤 이유로 추가하게 되었나요?

2024-07-23 15:24 UTC, uuujini commented on src/main/resources/application.yml
> +        dialect: org.hibernate.dialect.MySQL8Dialect
Hibernate Dialect 설정 누락으로 인해 빌드가 실패했다고 생각하여 추가했습니다!
알고 보니 DB 연결 문제였어서 이 부분은 다시 삭제하겠습니다!

2024-07-25 01:30 UTC, wnsvy607 approved these changes
LGTM 👍

2024-07-25 01:31 UTC, merged